### ISSUE TITLE
init.el line 775   (setq bookmark-default-file "~/.spacemacs.d/recentf")

### ISSUE THREAD

**Issue by garywei944** [practicalli/spacemacs-config#5]
It seems we have 
```
  (setq bookmark-default-file "~/.spacemacs.d/bookmarks")
```
at line 770 and
```
  (setq bookmark-default-file "~/.spacemacs.d/recentf")
```
at line 775. They use the same variable name. Is that a typo?

**Comment by practicalli-johnny** [comment]
Good spot, yes this was copy paste error, thank you.

I have pushed a commit with the correct setting.
